document.getElementById("year").textContent=new Date().getFullYear();
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener("click",()=>{const n=document.querySelector("nav");if(innerWidth<900)n.style.display="none"}));
const reveals=document.querySelectorAll(".reveal"),io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("show")}),{threshold:.12});reveals.forEach(x=>io.observe(x));setTimeout(()=>document.querySelectorAll(".hero .reveal").forEach(x=>x.classList.add("show")),100);

const SB_URL="https://rciscmvvfancpwsmpbtn.supabase.co",SB_KEY="sb_publishable_wbr5LFOBL0sPiNqBB43irw_W9Or5tvu",BUSINESS_ID="ca3d746f-3e73-4f7f-8377-f60d231745f3";
const db=window.supabase?.createClient(SB_URL,SB_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
function track(event_name){if(!db)return;db.from("mf_web_events").insert({business_id:BUSINESS_ID,event_name,page_path:location.pathname}).then(()=>{}).catch(()=>{})}
track("page_view");
document.querySelectorAll('a[href^="tel:"]').forEach(a=>a.addEventListener("click",()=>track("call_click")));
document.querySelectorAll('a[href^="sms:"]').forEach(a=>a.addEventListener("click",()=>track("text_click")));

const form=document.getElementById("quoteForm");let vehicle="",service="",started=false;
function step(n){form.querySelectorAll(".step").forEach(x=>x.classList.toggle("active",+x.dataset.step===n))}
function startQuote(){if(!started){started=true;track("quote_start")}}
form.querySelectorAll('[data-step="1"] [data-choice]').forEach(b=>b.onclick=()=>{startQuote();vehicle=b.dataset.choice;step(2)});
form.querySelectorAll('[data-step="2"] [data-choice]').forEach(b=>b.onclick=()=>{service=b.dataset.choice;step(3)});
form.querySelectorAll(".back").forEach((b,i)=>b.onclick=()=>step(i?2:1));
document.querySelectorAll(".service button").forEach(b=>b.onclick=()=>{service=b.dataset.service;document.getElementById("book").scrollIntoView();step(1)});
form.onsubmit=async e=>{
 e.preventDefault();const n=document.getElementById("name").value.trim(),p=document.getElementById("phone").value.trim(),c=document.getElementById("city").value.trim(),submit=form.querySelector('button[type="submit"]');
 if(!n||!p||!c||!vehicle||!service)return;
 submit.disabled=true;submit.textContent="Sending Request…";
 let saved=false;
 if(db){const {error}=await db.from("mf_estimate_requests").insert({business_id:BUSINESS_ID,name:n,phone:p,city:c,vehicle_size:vehicle,service,status:"new"});saved=!error;if(error)console.error("Estimate request could not be saved",error)}
 if(saved)track("estimate_submit");
 document.getElementById("summary").textContent=saved?n+", your estimate request was sent to Mighty Fine. You can also text us below if you'd like.":n+", your request is ready to text to Mighty Fine.";
 const msg=encodeURIComponent("Hi! I'm "+n+". I'd like a quote for a "+service+" on my "+vehicle+". I'm located in "+c+".");
 document.getElementById("textRequest").href="sms:+13306415559?&body="+msg;step(4);submit.disabled=false;submit.textContent="Send My Estimate Request →";
};
document.querySelector(".restart").onclick=()=>{vehicle="";service="";started=false;form.reset();step(1)};

const cmp=document.getElementById("compare"),bef=document.getElementById("before"),hand=document.getElementById("handle");function slide(x){const r=cmp.getBoundingClientRect(),pct=Math.max(2,Math.min(98,(x-r.left)/r.width*100));bef.style.width=pct+"%";hand.style.left=pct+"%"}cmp.addEventListener("pointermove",e=>{if(e.buttons)slide(e.clientX)});cmp.addEventListener("pointerdown",e=>{cmp.setPointerCapture(e.pointerId);slide(e.clientX)});
document.querySelector(".hamb").onclick=()=>{const nav=document.querySelector("nav");nav.style.display=nav.style.display==="flex"?"none":"flex";Object.assign(nav.style,{position:"absolute",top:"84px",left:"0",right:"0",padding:"25px",background:"#0b0e12",flexDirection:"column"})};

// Reviews section + slightly softer service ticker. Review copy intentionally stays
// source-based until exact Google/Facebook review text is supplied so the site never
// presents invented customer testimonials.
(()=>{
 const style=document.createElement("style");style.id="mf-review-styles";style.textContent=`
 .ticker div{color:#c7d1dc!important;animation-duration:25s!important}.ticker i{color:#53c3ff!important}
 .reviews{position:relative;overflow:hidden;background:radial-gradient(circle at 18% 12%,rgba(22,169,255,.13),transparent 30%),linear-gradient(180deg,#090d12,#07090c);border-top:1px solid var(--line);border-bottom:1px solid var(--line)}
 .reviews:before{content:"";position:absolute;width:430px;height:430px;border-radius:50%;right:-170px;bottom:-230px;background:rgba(22,169,255,.08);filter:blur(70px);pointer-events:none}
 .reviewHead{display:flex;align-items:end;justify-content:space-between;gap:44px;margin-bottom:42px}.reviewHead h2{font-size:clamp(48px,5vw,76px);letter-spacing:-3px;margin:18px 0 0}.reviewHead>p{max-width:430px;color:var(--muted);line-height:1.7;margin:0}
 .reviewOverview{display:grid;grid-template-columns:240px 1fr;gap:16px;align-items:stretch}.reviewScore{border:1px solid #2b3742;background:linear-gradient(145deg,rgba(17,28,37,.96),rgba(10,14,19,.96));border-radius:18px;padding:30px;display:flex;flex-direction:column;justify-content:center;min-height:270px;box-shadow:0 18px 50px rgba(0,0,0,.24)}.reviewScore strong{font-size:60px;letter-spacing:-3px;line-height:1}.reviewStars{color:#ffc928;letter-spacing:3px;font-size:17px;margin:12px 0 8px}.reviewScore small{color:#8794a1;line-height:1.5}.reviewSourceRow{display:flex;gap:8px;flex-wrap:wrap;margin-top:20px}.reviewSourcePill{display:inline-flex;align-items:center;gap:7px;border:1px solid #34414d;border-radius:999px;padding:8px 11px;font-size:10px;color:#c5d0da;background:#0a0e13}.reviewSourcePill b{display:grid;place-items:center;width:18px;height:18px;border-radius:50%;background:#f6f8fb;color:#111;font-size:11px}.reviewSourcePill.fb b{background:#1877f2;color:white}
 .reviewRailWrap{position:relative;min-width:0}.reviewRail{display:grid;grid-auto-flow:column;grid-auto-columns:minmax(265px,1fr);grid-template-rows:1fr;gap:12px;overflow-x:auto;scroll-snap-type:x mandatory;scrollbar-width:none;padding:0 1px 4px}.reviewRail::-webkit-scrollbar{display:none}.reviewCard{scroll-snap-align:start;border:1px solid #293541;border-radius:18px;padding:28px;background:linear-gradient(160deg,rgba(19,25,32,.96),rgba(11,15,20,.96));min-height:270px;display:flex;flex-direction:column;box-shadow:0 18px 45px rgba(0,0,0,.18);transition:transform .25s,border-color .25s}.reviewCard:hover{transform:translateY(-4px);border-color:#3b596c}.reviewCard .source{display:flex;align-items:center;gap:10px;font-size:12px;font-weight:800}.sourceLogo{width:28px;height:28px;border-radius:50%;display:grid;place-items:center;background:#f6f8fb;color:#111;font-weight:900}.sourceLogo.fb{background:#1877f2;color:#fff}.reviewCard .stars{color:#ffc928;letter-spacing:2px;margin:24px 0 18px}.reviewCard h3{font-size:20px;margin:0 0 10px}.reviewCard p{font-size:13px;line-height:1.75;color:#9ca8b5;margin:0 0 24px}.reviewCard a{margin-top:auto;color:var(--blue2);font-size:12px;font-weight:800}.reviewCard a:hover{color:#fff}.reviewNav{display:flex;align-items:center;justify-content:center;gap:9px;margin-top:20px}.reviewNav button{width:38px;height:38px;border-radius:50%;border:1px solid #33414e;background:#0e141a;color:#dce4eb;font-size:19px}.reviewNav button:hover{border-color:#4f83a3;background:#102433}.reviewDots{display:flex;gap:6px}.reviewDots i{width:6px;height:6px;border-radius:50%;background:#3a4652;transition:.2s}.reviewDots i.active{width:18px;border-radius:10px;background:var(--blue)}
 .reviewFoot{display:flex;justify-content:center;gap:10px;flex-wrap:wrap;margin-top:28px}.reviewFoot a{border:1px solid #34404b;padding:11px 16px;border-radius:9px;font-size:12px;font-weight:700;color:#c9d3dc}.reviewFoot a:first-child{background:#f7f8fa;color:#111;border-color:#f7f8fa}.reviewFoot a:hover{transform:translateY(-1px)}
 @media(min-width:1050px){.reviewRail{grid-auto-columns:calc((100% - 24px)/3)}}
 @media(max-width:900px){.reviewHead{display:block}.reviewHead>p{margin-top:22px}.reviewOverview{grid-template-columns:1fr}.reviewScore{min-height:auto}.reviewRail{grid-auto-columns:minmax(76%,1fr)}}
 @media(max-width:560px){.reviewRail{grid-auto-columns:88%}.reviewCard{min-height:250px;padding:24px}.reviewScore{padding:24px}.reviewScore strong{font-size:50px}.reviewNav{margin-top:16px}}
 @media(prefers-reduced-motion:reduce){.ticker div{animation:none!important}.reviewRail{scroll-behavior:auto!important}}
 `;document.head.appendChild(style);
 const work=document.getElementById("work");if(!work)return;
 const section=document.createElement("section");section.id="reviews";section.className="reviews section";
 section.innerHTML=`<div class="reviewHead reveal"><div><span class="kicker">REAL CUSTOMER FEEDBACK</span><h2>What people are<br><em>saying.</em></h2></div><p>Real customer feedback matters. This section is built for Mighty Fine's Google reviews and Facebook recommendations without turning the page into a wall of text.</p></div><div class="reviewOverview"><aside class="reviewScore reveal"><span class="kicker">CUSTOMER RATING</span><strong>5.0</strong><div class="reviewStars" aria-label="5 out of 5 stars">★★★★★</div><small>Current public customer rating. Individual review excerpts will only be shown when they can be tied to the original review.</small><div class="reviewSourceRow"><span class="reviewSourcePill"><b>G</b>Google</span><span class="reviewSourcePill fb"><b>f</b>Facebook</span></div></aside><div class="reviewRailWrap reveal"><div class="reviewRail" id="reviewRail"><article class="reviewCard"><div class="source"><span class="sourceLogo">G</span>Google Reviews</div><div class="stars">★★★★★</div><h3>See our latest Google feedback</h3><p>Open Mighty Fine's Google listing to read the newest customer reviews directly from the source.</p><a href="https://www.google.com/maps/search/?api=1&query=Mighty%20Fine%20Detailing%20Rittman%20OH" target="_blank" rel="noopener">Read Google reviews →</a></article><article class="reviewCard"><div class="source"><span class="sourceLogo fb">f</span>Facebook</div><div class="stars">★★★★★</div><h3>Customer recommendations</h3><p>See recommendations and community feedback for Mighty Fine Detailing on Facebook.</p><a href="https://www.facebook.com/search/top/?q=Mighty%20Fine%20Detailing%20LLC" target="_blank" rel="noopener">View Facebook feedback →</a></article><article class="reviewCard"><div class="source"><span class="sourceLogo">★</span>Mighty Fine</div><div class="stars">★★★★★</div><h3>Had a Mighty Fine experience?</h3><p>Your feedback helps a local business grow and helps the next customer feel confident booking their detail.</p><a href="https://www.google.com/maps/search/?api=1&query=Mighty%20Fine%20Detailing%20Rittman%20OH" target="_blank" rel="noopener">Leave a review →</a></article></div><div class="reviewNav"><button type="button" id="reviewPrev" aria-label="Previous review">‹</button><span class="reviewDots" id="reviewDots"><i class="active"></i><i></i><i></i></span><button type="button" id="reviewNext" aria-label="Next review">›</button></div></div></div><div class="reviewFoot reveal"><a href="https://www.google.com/maps/search/?api=1&query=Mighty%20Fine%20Detailing%20Rittman%20OH" target="_blank" rel="noopener">Google Reviews</a><a href="https://www.facebook.com/search/top/?q=Mighty%20Fine%20Detailing%20LLC" target="_blank" rel="noopener">Facebook Recommendations</a></div>`;
 work.insertAdjacentElement("afterend",section);
 section.querySelectorAll(".reveal").forEach(x=>io.observe(x));
 const rail=document.getElementById("reviewRail"),cards=[...rail.children],dots=[...document.querySelectorAll("#reviewDots i")];let current=0,autoTimer;
 const go=n=>{current=(n+cards.length)%cards.length;rail.scrollTo({left:cards[current].offsetLeft-rail.offsetLeft,behavior:"smooth"});dots.forEach((d,i)=>d.classList.toggle("active",i===current))};
 document.getElementById("reviewPrev").onclick=()=>{go(current-1);restartAuto()};document.getElementById("reviewNext").onclick=()=>{go(current+1);restartAuto()};dots.forEach((d,i)=>d.onclick=()=>{go(i);restartAuto()});
 const restartAuto=()=>{clearInterval(autoTimer);if(matchMedia("(max-width:900px)").matches&&!matchMedia("(prefers-reduced-motion: reduce)").matches)autoTimer=setInterval(()=>go(current+1),7500)};restartAuto();
 rail.addEventListener("pointerdown",()=>clearInterval(autoTimer));rail.addEventListener("pointerup",restartAuto);window.addEventListener("resize",restartAuto);
})();
